site_name: Quality Updates
site_url: https://quality-updates.onrender.com/

theme:
  name: material
  language: ko
  logo: assets/images/clip.png
  favicon: assets/images/clip.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow

nav:
  - 홈: index.md

  - 규제 업데이트:
      - 2023:
          - quality-updates/2023/2023-09-30_to_2023-12-31.md
          - quality-updates/2023/2023-08-31_to_2023-09-30.md
          - quality-updates/2023/2023-07-14_to_2023-08-31.md
          - quality-updates/2023/2023-05-08_to_2023-07-14.md
          - quality-updates/2023/2023-04-03_to_2023-05-08.md

      - 2022:
          - quality-updates/2022/2022-12-15_to_2023-04-03.md

  - 품질관리감리:
      - fss-review/fr2022.md

markdown_extensions:
  - toc:
      permalink: '#'
      toc_depth: 2-6
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js
