site_name: Quality-Updates
site_url: https://quality-updates.onrender.com/

theme:
  name: material
  custom_dir: overrides
  favicon: ./assets/images/clip.png

nav:    
    - 관련 정보:
      - 2022:
          - '12.15. - 4.3.': ./qualityUpdate/221215-230403.md
      - 2023:
          - '4.3. - 5.8.': ./qualityUpdate/230403-230508.md
          - '5.8. - 7.14.': ./qualityUpdate/230508-230714.md
          - '7.14. - 8.31.': ./qualityUpdate/230714-230831.md
          - '8.31. - 9.30.': ./qualityUpdate/230831-230930.md
    - 품질관리감리: ./fssReview/fr2022.md


markdown_extensions:
    - toc:
        permalink: '#'
        baselevel: 1
        toc_depth: 2-6
    - attr_list
    - footnotes
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - md_in_html
    - pymdownx.tabbed:
        alternate_style: true     
  
plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  